# Default values for destinyarena.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Discord Bot
bot:
  name: bot
  replicas: 1
  image: destinyarena/bot:latest

  service:
    type: ClusterIP

  secret: bot-secrets
  secrets:
    - name: AUTH_TOKEN
      value: auth-token
    - name: DISCORD_TOKEN
      value: discord-token
    - name: FACEIT_USER_TOKEN
      value: faceit-user-token
    - name: FACEIT_API_TOKEN
      value: faceit-api-token

tls:
  enabled: false

# API
api:
  name: api
  replicas: 2
  image: destinyarena/api:latest

  service:
    type: LoadBalancer

  secret: api-secrets
  secrets:
    - name: SECRET_DISCORD
      value: discord
    - name: SECRET_FACEIT
      value: faceit
    - name: SECRET_FACEIT_API_KEY
      value: faceit-api-key
    - name: SECRET_FACEIT_USER_KEY
      value: faceit-user-key
    - name: SECRET_BUNGIE
      value: bungie
    - name: SECRET_BUNGIE_API_KEY
      value: bungie-api-key
    - name: SECRET_JWT
      value: jwt
    - name: SECRET_API_KEY
      value: api-key
    - name: SECRET_DB_PASSWORD
      value: db-password

# Website
website:
  name: website
  replicas: 2
  image: destinyarena/website:latest

  service:
    type: LoadBalancer

# Users gRPC
profiles:
  name: profiles
  replicas: 2
  image: destinyarena/profiles:latest
  secret: profiles-secrets
  secrets:
    - name: SECRET_DB_PASSWORD
      value: db-password

# Faceit gRPC
faceit:
  name: faceit
  replicas: 2
  image: destinyarena/faceit:latest
  secret: faceit-secrets
  secrets:
    - name: FACEIT_USER_TOKEN
      value: faceit-user-key
    - name: FACEIT_API_TOKEN
      value: faceit-api-key

ingress:
  name: destinyarena
  host: destinyarena.app
  paths:
    - path: "/api/"
      service: api
      port: 80
    - path: "/"
      service: website
      port: 80
