# Default values for destinyarena.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Discord Bot
bot:
  name: bot
  replicas: 1
  image:
    repository: harbor.ar2ro.io/destinyarena/bot
    tag: 015a169f83971e14509339f5ad1d00a83e786ed6
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  secret: bot-secrets
  secrets:
    - name: AUTH_TOKEN
      value: auth-token
    - name: DISCORD_TOKEN
      value: discord-token
    - name: FACEIT_USER_TOKEN
      value: faceit-user-token
    - name: FACEIT_API_TOKEN
      value: faceit-api-token
tls:
  enabled: false
# Website
website:
  name: website
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/website
    tag: 54877e6a33b0ef30bd739702290a30cf96a262a4
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
# Users gRPC
profiles:
  name: profiles
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/profiles
    tag: d60e7ffa1b3930f4d6f8a84e754c3efc3b9a68b2
    pullPolicy: IfNotPresent
  secret: profiles-secrets
  secrets:
    - name: SECRET_DB_PASSWORD
      value: db-password
# Faceit gRPC
faceit:
  name: faceit
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/faceit
    tag: 7ddd406ed0ac102e901541ffb2f581d2da825aee
    pullPolicy: IfNotPresent
  secret: faceit-secrets
  secrets:
    - name: FACEIT_USER_TOKEN
      value: faceit-user-key
    - name: FACEIT_API_TOKEN
      value: faceit-api-key
authorization:
  name: authorization
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/authorization
    tag: 3b4fd06a1885dd7be2abf55efb7b4d2ac68dcfa2
    pullPolicy: IfNotPresent
registration:
  name: registration
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/registration
    tag: 8a60a7b8216c94fdeeabe7045e859ba9926a8962
    pullPolicy: IfNotPresent
ingress:
  name: destinyarena
  host: destinyarena.app
  paths:
    - path: "/api/v2/oauth/"
      service: authorization
      port: 80
    - path: "/api/v2/registration"
      service: registration
      port: 80
    - path: "/api/"
      service: api
      port: 80
    - path: "/"
      service: website
      port: 80
