# Default values for destinyarena.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Discord Bot
bot:
  name: bot
  replicas: 1
  image:
    repository: harbor.ar2ro.io/destinyarena/bot
    tag: 62bd7f6d57daf56a39fc0bb74c5793c5c6a11a08
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  secret: bot-secrets
  secrets:
    - name: AUTH_TOKEN
      value: auth-token
    - name: DISCORD_TOKEN
      value: discord-token
    - name: FACEIT_USER_TOKEN
      value: faceit-user-token
    - name: FACEIT_API_TOKEN
      value: faceit-api-token
tls:
  enabled: false
# Website
website:
  name: website
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/website
    tag: 29823dc737ed66e624f8c19d49fecdff903999b8
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
# Users gRPC
profiles:
  name: profiles
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/profiles
    tag: 35ca9cf68143f549a8b3b58d77ce74e31d57ef99
    pullPolicy: IfNotPresent
  secret: profiles-secrets
  secrets:
    - name: SECRET_DB_PASSWORD
      value: db-password
# Faceit gRPC
faceit:
  name: faceit
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/faceit
    tag: 9c20f30585b69a525a36365587856889f19fbb3c
    pullPolicy: IfNotPresent
  secret: faceit-secrets
  secrets:
    - name: FACEIT_USER_TOKEN
      value: faceit-user-key
    - name: FACEIT_API_TOKEN
      value: faceit-api-key
authorization:
  name: authorization
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/authorization
    tag: 3b4fd06a1885dd7be2abf55efb7b4d2ac68dcfa2
    pullPolicy: IfNotPresent
registration:
  name: registration
  replicas: 2
  image:
    repository: harbor.ar2ro.io/destinyarena/registration
    tag: 2222ba9e3e6c62ef855091edccde65eab93cf3dc
    pullPolicy: IfNotPresent
ingress:
  name: destinyarena
  host: destinyarena.app
  paths:
    - path: "/api/v2/oauth/"
      service: authorization
      port: 80
    - path: "/api/v2/registration"
      service: registration
      port: 80
    - path: "/api/"
      service: api
      port: 80
    - path: "/"
      service: website
      port: 80
