{{- with .Values.faceit }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: tcp-faceit
      port: 8080
      protocol: TCP
      targetPort: 8080
{{- end }}
