{{- with .Values.faceit }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
            {{- range .secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.faceit.secret }}
                  key: {{ .value }}
            {{- end }}
{{- end }}
