{{- with .Values.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: tcp-api
      port: 80
      targetPort: 8080
{{- end }}
