{{- with .Values.bot }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: tcp-bot
      port: 80
      targetPort: 8080
{{- end }}
