{{- with .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  rules:
    - http:
        paths:
          {{- range .paths }}
          - path: {{ quote .path }}
            backend:
              serviceName: {{  .service }}
              servicePort: 80
          {{- end }}
{{- end }}
