{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  rules:
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{  .service }}
              servicePort: {{  .port }}
          {{- end }}
      {{- if .host }}
      host: {{ .host }}
      {{- end }}
{{- end }}
