apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authorization.name }}
spec:
  selector:
    app: {{ .Values.authorization.name }}
  ports:
    - name: tcp-authorization
      port: 80
      targetPort: 8080
