apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authorization.name }}
  labels:
    app: {{ .Values.authorization.name }}
spec:
  replicas: {{ .Values.authorization.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.authorization.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.authorization.name }}
    spec:
      containers:
        - name: {{ .Values.authorization.name }}
          image: {{ .Values.authorization.image }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
          envFrom:
            - configMapRef:
                name: {{ .Values.authorization.name }}
